# Generated by Django 3.2.4 on 2021-07-02 07:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=20, verbose_name='Mã máy')),
                ('location', models.CharField(max_length=50, verbose_name='Nhà máy')),
                ('machine_name', models.CharField(max_length=200, verbose_name='Tên Máy')),
                ('clamping_force', models.IntegerField(verbose_name='Số Tấn')),
                ('robot', models.CharField(blank=True, max_length=200, verbose_name='Tay Robot')),
                ('dry_machine', models.CharField(blank=True, max_length=200, verbose_name='Máy Sấy Nhựa')),
                ('hot_water', models.CharField(blank=True, max_length=200, verbose_name='Máy Nước Nóng')),
                ('covey_bell', models.CharField(blank=True, max_length=100, verbose_name='Băng Tải')),
                ('update_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mold_code', models.CharField(max_length=200, verbose_name='Mã Khuôn')),
                ('mold_weight', models.IntegerField(verbose_name='Trọng Lượng Khuôn')),
                ('cavity', models.IntegerField(verbose_name='Số Cavity Nghiệm thu')),
                ('check_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=200, verbose_name='Mã Sản Phẩm')),
                ('product_name', models.CharField(max_length=200, verbose_name='Tên Sản Phẩm Đầy Đủ')),
                ('customer', models.CharField(max_length=200, verbose_name='Khách Hàng')),
                ('shot_weight', models.FloatField(verbose_name='Trọng Lượng Shot')),
                ('product_weight', models.FloatField(verbose_name='Trọng Lượng Sản Phẩm')),
                ('NG_rate', models.FloatField(default=0.03, verbose_name='Tỷ lệ NG cho phép')),
                ('max_day', models.IntegerField(verbose_name='SL Max day')),
                ('production_cycle', models.FloatField(verbose_name='Chu kỳ Chuẩn')),
                ('mold_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.mold', verbose_name='Mã Khuôn')),
            ],
        ),
        migrations.CreateModel(
            name='Dailyproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(default=datetime.datetime(2021, 7, 2, 7, 14, 10, 784858, tzinfo=utc))),
                ('cavity', models.IntegerField(verbose_name='Số Cavity SX')),
                ('production_time', models.IntegerField(verbose_name='Thời gian SX')),
                ('product_cycle', models.FloatField(verbose_name='Chu kỳ sản xuất')),
                ('good_quantity', models.IntegerField(verbose_name='Số lượng OK')),
                ('NG_quantity', models.IntegerField(verbose_name='Số lượng hàng NG')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.machine')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.product')),
            ],
        ),
    ]
