# Generated by Django 3.2.4 on 2021-07-02 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproduction',
            name='production_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
